class RoutePaths {
  static const String LOGIN = 'login';
  static const String HOME = 'home';
  static const String FORGOT='forgot';
  static const String CHANGENEWPASSWORD='changepass';
  static const String SIGNUP='signup';
  static const String OTPVERIFICATION='otpverify';
  static const String BOTTOMNAVIGATION='bottomnavigation';
  static const String FAMILYMEMEBER='familymemberscreen';
  static const String APPOINTMENTSCREEN='appointmentscreen';
  static const String DrPROFILE='profile';
  static const String Appointment='appointemnt';
  static const String Appointment_Done='appointemnt_done';
  static const String Token='token';
  static const String Token_Done='token_done';
  static const String Doctor_Profile_token='doctor_profile_token';
  static const String Pin_Set='pin_set';
  static const String Notification='notify';
  static const String NoOFAppointment='NoOFAppointment';
  static const String Setting='Setting';
  static const String Health_Record='health Record';
  static const String My_Doctor='My_Doctor';
  static const String HomeScreen='Home_Screen';
  static const String Prescription='Prescription';
  static const String Change_New_Password_setting='Change_New_Password_setting';
  static const String Pharmacy='Pharmacy';
  static const String Add_Family__Member='Add_Family_Member';
  static const String Log_In_Setting='Log_In_Setting';
}
